import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className="bg-gray-100 text-gray-900 min-h-screen flex flex-col">
        <main className="flex-grow p-4">{children}</main>
        <footer className="bg-gray-800 text-white py-8 mt-auto">
          <div className="container mx-auto text-center">
            <p>&copy; 2024 AJ StockManager. Todos los derechos reservados.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
